# Dockerfile.simulator
FROM python:3.11-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar requirements
COPY requirements.txt .

# Instalar dependencias Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el script del simulador
COPY sensor_simulator.py .

# Variable de entorno para Python sin buffer
ENV PYTHONUNBUFFERED=1

# Comando por defecto
CMD ["python", "-u", "sensor_simulator.py"]